### ISSUE TITLE
Doesn't work with Monterey?

### ISSUE THREAD

**Issue by teddis** [jduerr/FCPX-Chapter-Extractor#2]
Unfortunately, this appears to be incompatible with the latest Mac OS. The Finder says that the AutomatorFCPXExtractor.app is damaged. The service seems to install but doesn't appear in the Finder menu, perhaps related to the former issue?

**Comment by jduerr** [comment]
Ok, sorry for the inconvenience!
I just exported a current version, sadly i can not test with Monerey since i'm still running Big Sur on my macs. 
Could you please checkout the current commit i pushed to the master branch and retry it?

Also - could you please verify that python is installed on your machine?

kind regards

Johannes

**Comment by teddis** [comment]
Hi, thanks for quick reply! Mac has python2.7 installed by default and it looks like I can't even remove the symlink as root! Your update still fails for me. I get the following still when running the app:

"FCPXML-
Chapter_Standalone.app" is
damaged and can't be opened.
You should move it to the Trash."

So I wonder if python2.7 is too old for your app? Is there a way to specify the location of python in your app if it's required? What version is required?

**Comment by jduerr** [comment]
Using macOS 11.6.2, python version 2.7.16 is preinstalled in /usr/bin/python, too. So can't see any difference there. 
Yes, opening the workflow will lead to opening it in Automator, where you can see what exactly is being done. 
The workflow is receiving files from finder and handing them over to the python script as arguments.

Thy python script does the heavy lifting and outputs the text as string to the last step: ... saving the text (string) into a text file.

If using the automator workflow you could test it by adding your *.fcpxml file to the first step (Get specified finder items) directly in automator and hitting the "Run" button in the toolbars top right corner. 
<img width="847" alt="Bildschirmfoto 2022-02-04 um 05 47 52 AM" src="https://user-images.githubusercontent.com/1424072/152473808-5e490949-ba8f-41f3-bc92-4a89cb7baa4c.png">

One thing i noticed, ... of course the extractor is working only with *.fcpxml files. It does not work with *.fcpxmld format. But the error message would be different if that would be the problem.

**Comment by duncangroenewald** [comment]
It's not working for me either.  I can run the script from automator but the output file is empty.

**Comment by AdamMannPro** [comment]
Hi, Im still having the same issues as the above, I have modded the automator file but when running it, it says I need to install the app again. it will not run from Finder either.

Such a pity as this app was so helpful for my vlogs.

If there is anything I can do to help get this working I would be willing to do any testing or provide any further information. I am running macOS Monterey on a 2018 MBP.

**Comment by AdamMannPro** [comment]
Found a work around that works.

https://www.alfredapp.com/help/kb/python-2-monterey/

Just tested it myself and got it working.

Installed Homebrew and ran the terminal command on the site and it works, not the best workaround but until it is tested and resolved by the creator this will have to do.

**Comment by swift2geek** [comment]
Here is a working tool for Macos Ventura https://github.com/swift2geek/fcpx-extractor
